
services:
  maxkb:
    image: 1panel/maxkb
    container_name: maxkb
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - my_env/network.env
    volumes:
      - ~/.maxkb:/var/lib/postgresql/data
      - ~/.python-packages:/opt/maxkb/app/sandbox/python-packages
